# Generated by Django 6.0.6 on 2026-06-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('tavsifi', models.TextField(blank=True, null=True)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chegirmadagi_narxi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ombordagi_soni', models.IntegerField(default=0)),
                ('aktiv_holati', models.BooleanField(default=True)),
                ('yaratilgan_vaqti', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqti', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
